// Style keys verified byte-identical across every upload/JV page (Sales,
// Bills, Payroll, Inventory, Store Transfer, Manual JV) before extraction —
// each page spreads `...sharedPageStyles` into its own `styles` object and
// keeps only the values that genuinely differ (banners, table cell sizing,
// field inputs, etc.) locally. Purely a duplication cut, no visual change.
export const sharedPageStyles = {
  loadingScreen: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--ink-soft)",
  },
  shell: { display: "flex", minHeight: "100vh" },
  topRow: { marginBottom: 20 },
  h1: { fontFamily: "var(--font-display)", fontSize: 26, margin: 0 },
  card: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  dropzoneActive: { borderColor: "var(--ledger)", background: "rgba(34,163,123,0.06)" },
  dropzoneText: { fontSize: 13, color: "var(--ink-soft)" },
  previewBtn: {
    background: "var(--danger)",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 600,
  },
  xlsxBtn: {
    background: "var(--accent-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 600,
  },
  csvBtnMuted: {
    background: "transparent",
    color: "var(--ink-soft)",
    border: "1px solid var(--line)",
    borderRadius: 7,
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 600,
  },
  resultsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    gap: 12,
  },
  selectAllLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--ink-soft)",
    fontWeight: 600,
    cursor: "pointer",
  },
  companyCheckLabel: { display: "flex", alignItems: "center", gap: 10, cursor: "pointer" },
  tr: { borderBottom: "1px solid var(--line)" },
  companyGrid: { display: "flex", flexDirection: "column", gap: 5 },
  companyCard: {
    background: "var(--panel)",
    border: "1px solid var(--line)",
    borderRadius: 6,
    padding: "7px 14px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  companyName: { fontFamily: "var(--font-display)", fontWeight: 600, fontSize: 12.5 },
  secondaryBtn: {
    background: "transparent",
    color: "var(--ink)",
    border: "1px solid var(--line)",
    borderRadius: 5,
    padding: "5px 10px",
    fontSize: 11,
    fontWeight: 600,
  },

  // Accounting/Reconciliation mode toggle — added 2026-08-18 to Sales,
  // Store Transfer, and all 3 Bills tabs, so a file whose dates span more
  // than one month (a year-to-date export, for cross-checking) can be
  // loaded without tripping the normal single-Month upload gate.
  modeToggleRow: { display: "flex", gap: 8 },
  modeBtn: {
    background: "transparent",
    color: "var(--ink-soft)",
    border: "1px solid var(--line)",
    borderRadius: 7,
    padding: "10px 14px",
    fontSize: 12.5,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  modeBtnActive: { background: "var(--ledger)", color: "#fff", borderColor: "var(--ledger)" },
  reconciliationNote: {
    background: "var(--warn-bg)",
    color: "var(--warn-text)",
    padding: "10px 14px",
    borderRadius: 6,
    fontSize: 12.5,
    marginTop: 12,
    lineHeight: 1.5,
  },
};
